issuer: Government of Maharashtra - Application for Intimation
keywords:
  - Form - 'F'
  - APPLICATION FOR INTIMATION
fields:
  name_of_establishment: Name of the establishment(?:[\S\s]*?)([A-Z \.]{8,})\s*
  name_of_employer: Name of the Employer(?:[\S\s]*?)([A-Z \.]{8,})\s*